# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import smalltalk_pb2 as smalltalk__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in smalltalk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SmallTalkServiceStub(object):
    """Сервис для взаимодействия между хостами
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTask = channel.unary_unary(
                '/smalltalk.SmallTalkService/GetTask',
                request_serializer=smalltalk__pb2.TaskRequest.SerializeToString,
                response_deserializer=smalltalk__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/smalltalk.SmallTalkService/CompleteTask',
                request_serializer=smalltalk__pb2.CompleteRequest.SerializeToString,
                response_deserializer=smalltalk__pb2.CompleteResponse.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/smalltalk.SmallTalkService/UpdateStatus',
                request_serializer=smalltalk__pb2.StatusRequest.SerializeToString,
                response_deserializer=smalltalk__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/smalltalk.SmallTalkService/Ping',
                request_serializer=smalltalk__pb2.PingRequest.SerializeToString,
                response_deserializer=smalltalk__pb2.PingResponse.FromString,
                _registered_method=True)


class SmallTalkServiceServicer(object):
    """Сервис для взаимодействия между хостами
    """

    def GetTask(self, request, context):
        """Запрос задачи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Сообщение о завершении задачи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Обновление состояния
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Проверка соединения
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmallTalkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=smalltalk__pb2.TaskRequest.FromString,
                    response_serializer=smalltalk__pb2.TaskResponse.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=smalltalk__pb2.CompleteRequest.FromString,
                    response_serializer=smalltalk__pb2.CompleteResponse.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=smalltalk__pb2.StatusRequest.FromString,
                    response_serializer=smalltalk__pb2.StatusResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=smalltalk__pb2.PingRequest.FromString,
                    response_serializer=smalltalk__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smalltalk.SmallTalkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smalltalk.SmallTalkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmallTalkService(object):
    """Сервис для взаимодействия между хостами
    """

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smalltalk.SmallTalkService/GetTask',
            smalltalk__pb2.TaskRequest.SerializeToString,
            smalltalk__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smalltalk.SmallTalkService/CompleteTask',
            smalltalk__pb2.CompleteRequest.SerializeToString,
            smalltalk__pb2.CompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smalltalk.SmallTalkService/UpdateStatus',
            smalltalk__pb2.StatusRequest.SerializeToString,
            smalltalk__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smalltalk.SmallTalkService/Ping',
            smalltalk__pb2.PingRequest.SerializeToString,
            smalltalk__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
